# .github/workflows/main_bdedekweb1754384158.yml

name: Build and Deploy Docker App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_SECRET_NAME }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_SECRET_NAME }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_SECRET_NAME }}

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.AZURE_WEBAPP_NAME }}.azurecr.io/bdedektif:${{ github.sha }}
          docker push ${{ secrets.AZURE_WEBAPP_NAME }}.azurecr.io/bdedektif:${{ github.sha }}
        env:
          AZURE_WEBAPP_NAME: bdedekweb1754384158

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdedekweb1754384158'
          images: '${{ secrets.AZURE_WEBAPP_NAME }}.azurecr.io/bdedektif:${{ github.sha }}'
