# .github/workflows/maint_bdedekweb1754384158.yml

name: Build and Deploy Python App to Azure Web App

on:
  push:
    branches:
      - maint
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m venv --copies venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: . # Tüm dosyaları ve kurulan bağımlılıkları içeren venv'i dahil et

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_SECRET_NAME }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_SECRET_NAME }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_SECRET_NAME }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdedekweb1754384158'
          package: .
